### ISSUE TITLE
Meaningful Repositories

### ISSUE THREAD

**Issue by jamiecounsell** [jacksoncwwong/week-3#1]
Don't get lazy with repositories! We can create as many as we want for a reason. Each individual project should have its own repository. For this, you should have a chat-app repository. This helps me (as another developer) navigate, comment on, improve, and read your code far more easily. This goes for Week2 and Week1.

**Comment by jacksoncwwong** [comment]
:P got it! LOL actually I was thinking of uploading my entire folder
containing all my projects as a repository... all due ot laziness lol. I
will amend that right now.

On Tuesday, June 23, 2015, Jamie Counsell <notifications@github.com> wrote:

> Don't get lazy with repositories! We can create as many as we want for a
> reason. Each individual project should have its own repository. For this,
> you should have a chat-app repository. This helps me (as another developer)
> navigate, comment on, improve, and read your code far more easily. This
> goes for Week2 and Week1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacksoncwwong/week-3/issues/1>.
>


-- 
Jackson Wong

**Comment by jamiecounsell** [comment]
Sweet! Close this when it's done :dancer:

**Comment by jacksoncwwong** [comment]
hmmm i'm a little confused, what am I closing?

On Tuesday, June 23, 2015, Jamie Counsell <notifications@github.com> wrote:

> Sweet! Close this when it's done [image: :dancer:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacksoncwwong/week-3/issues/1#issuecomment-114590644>.
>


-- 
Jackson Wong

**Comment by jamiecounsell** [comment]
This issue!

**Comment by jacksoncwwong** [comment]
LOL got it, i thought it's just show me in my_profiles/issues but it's only
in jacksoncwwong/week-3/issues, is there a place to see all issues?

On Tuesday, June 23, 2015, Jamie Counsell <notifications@github.com> wrote:

> This issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacksoncwwong/week-3/issues/1#issuecomment-114594058>.
>


-- 
Jackson Wong
